# Generated by Django 5.1.3 on 2024-11-22 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('puesto', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id_peticion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=500)),
                ('prioridad', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('solucion', models.TextField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(default='En proceso', max_length=20)),
                ('empleado_peticion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MesaDeAyudaFESC.empleado')),
                ('tecnico_peticion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MesaDeAyudaFESC.tecnico')),
            ],
        ),
    ]
