# Generated by Django 5.1.3 on 2024-11-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MesaDeAyudaFESC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_tickets/'),
        ),
    ]
