# Generated by Django 5.1.3 on 2024-11-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MesaDeAyudaFESC', '0002_peticion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='status',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Testeo', 'Testeo'), ('Solucionado', 'Solucionado')], default='En proceso', max_length=20),
        ),
    ]
